name: Run All Tests

on:
  pull_request:
    paths:
      - '**.swift'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: SwiftyLab/setup-swift@latest
        with:
           swift-version: "6.1"

      - uses: useblacksmith/cache@v5
        with:
          path: .build
          key: ${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}

      - name: Run Unit Tests
        uses: GetAutomaApp/opensource-actions/swifttesting@main
        with:
          compose: "false"
          swift_test_extra_args: "--filter '.*UnitTests.*'"

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: SwiftyLab/setup-swift@latest
        with:
           swift-version: "6.1"

      - uses: useblacksmith/cache@v5
        with:
          path: .build
          key: ${{ runner.os }}-integrationtests-${{ hashFiles('**/Package.resolved') }}

      - name: Run Integration Tests
        uses: GetAutomaApp/opensource-actions/swifttesting@main
        with:
          compose: "false"
          swift_test_extra_args: "--filter '.*IntegrationTests.*'"

    env:
      PATH: "/usr/local/bin:/usr/bin:/bin"

